In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import datetime as dt

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,LSTM
import yfinance


In [41]:
yfinance.pdr_override()
company = "RELIANCE.NS"
start = "2013-1-1"
end = "2022-1-1"
df = web.get_data_yahoo(company,start=start,end=end)


[*********************100%***********************]  1 of 1 completed


In [42]:
df.tail()

Open         High          Low        Close    Adj Close  \
Date                                                                          
2021-12-27  2361.550049  2378.000000  2348.100098  2370.250000  2363.135254   
2021-12-28  2375.600098  2404.850098  2373.050049  2398.399902  2391.200684   
2021-12-29  2391.000000  2419.000000  2382.100098  2402.500000  2395.288330   
2021-12-30  2400.000000  2404.949951  2345.600098  2359.100098  2352.018799   
2021-12-31  2373.000000  2383.899902  2360.000000  2368.149902  2361.041504   

              Volume  
Date                  
2021-12-27   1853948  
2021-12-28   2941883  
2021-12-29   7118779  
2021-12-30  13537254  
2021-12-31   4373768

In [43]:
scaler = MinMaxScaler(feature_range=(0,1))

In [44]:
df['Close'].describe()

count    2220.000000
mean      986.808473
std       629.601374
min       380.171356
25%       472.991501
50%       714.527008
75%      1327.305939
max      2731.850098
Name: Close, dtype: float64

In [45]:
df['Close'].shape

(2220,)

In [46]:
reshape_close = df['Close'].values.reshape(-1,1)

In [47]:
print(reshape_close)

[[ 416.40292358]
 [ 419.99386597]
 [ 426.33377075]
 ...
 [2402.5       ]
 [2359.10009766]
 [2368.14990234]]


In [48]:
scaled_data = scaler.fit_transform(reshape_close)

In [49]:
scaled_data

array([[0.01540668],
       [0.01693365],
       [0.01962956],
       ...,
       [0.85995107],
       [0.84149621],
       [0.84534444]])

In [50]:
prediction_days = 60
x_train = []
y_train = []
for x in range(prediction_days,len(scaled_data)):
    x_train.append(scaled_data[x-prediction_days:x,0])
    y_train.append(scaled_data[x,0])

In [67]:
print(x_train.shape,y_train.shape)
# print(x_train[0:2])

(2160, 60) (2160,)


In [68]:
x_train,y_train = np.array(x_train),np.array(y_train)

In [72]:
x_train.shape

(2160, 60)

In [73]:
x_train = np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))

In [81]:
x_train

array([[[0.01540668],
        [0.01693365],
        [0.01962956],
        ...,
        [0.00948832],
        [0.00906709],
        [0.00878275]],

       [[0.01693365],
        [0.01962956],
        [0.01986125],
        ...,
        [0.00906709],
        [0.00878275],
        [0.00332775]],

       [[0.01962956],
        [0.01986125],
        [0.0187555 ],
        ...,
        [0.00878275],
        [0.00332775],
        [0.0011268 ]],

       ...,

       [[0.9114887 ],
        [0.92528733],
        [0.94784571],
        ...,
        [0.84732181],
        [0.84623746],
        [0.85820759]],

       [[0.92528733],
        [0.94784571],
        [0.92686076],
        ...,
        [0.84623746],
        [0.85820759],
        [0.85995107]],

       [[0.94784571],
        [0.92686076],
        [0.93219729],
        ...,
        [0.85820759],
        [0.85995107],
        [0.84149621]]])

In [82]:
model = Sequential()